### ISSUE TITLE
Why does the final image have four horizontal lines?

### ISSUE THREAD

**Issue by yangjunjie003** [ReplyTechnologies/zpl-image-convert#2]
This is the ZPL instruction I parsed
^GFA,1900,1900,19, ,::::W0H4H2W0,T0G6G2G3H1H8GCG4G6T0,Q0G2G3G1G0H8H4G2G3H1H8GCG4Q0Q0G2G0G1G0H8H4G2G0G1H0G8G0G4Q0Q0H8H4G2G0G1G0H8H4H2H1Q0O0G1G0H8G4G6G2G3H1H8H4H2H1G0G8O0,O0G4G6G2G3H1H8G4G6G2G3H1H8GCG4G6G2O0,N0G3G1H8GCG4G6G2G3H1H8GCG4G6G3H1H8GCN0,N0GCG4G6G2G3G1G0H8H4G2G3H1H8GCG4G6G2G1N0O0G4G0G2H1G0H8H4H2G1H0G8G0G4H2G1N0M0G2G1G9G0G8G0G4G0G2G0GDH0G8G0G4H2G1H0G8G0G4M0L0H2G1GDG0G8GCG4G6G2G3GFG1H8GCG4H2H1H8GCH4L0N0G1GEL0G3GCg0L0H8GDGFG6G2G3H1G8GFGCG6G2G3H1H8GCG4G6G2G3G1M0N0G1GFG8K0GFGCg0L0G6G2G1GFGCG8GCG4G6G3HFG1H8GCG4H2H1H8GCG4G6L0N0G1GFGEJ0G3GFGCg0K0G1G0G8GDHFG2H1G0HFGCG4H2H1H8GCG4H2H1G0G8K0K0G1G0G8G9HFGAH1G0HFGCG4H2H1G0G8H4H2H1G0G8K0K0G4G0G2G1NFGDH0G8G0G4H0G1H0G8G0G4G0G2K0K0G4G6G2G1OFG1H8GCG4H2H1H8GCG4G6G2K0N0G1NFGCg0J0H1H8GDNFGCG6G2G3H1H8GCG4G6G2G3G1G0G8GCJ0N0G1NFGCg0J0H4G6G2G1GFGCG3IFG0HFG1H8GCG4H2H1H8GCG4G6G2K0N0G1GFG8G0HFG8G0GFGCS0G6L0J0H1G0G8GDGFGCG0G3GFG0G1GFGCG4H2H1H8GCG4H2G1G3GFH8J0J0H1G0G8GCHFGCG3GFG1HFGCG4H2H1H8GCG4H2G3HFH8J0N0G1NFGCQ0G7HFL0J0GCG4G6G2G1NFGDG1H8GCG4H2H1G8G9IFG2G3J0O0NFGCP0JFL0J0H1H8GCG7MFGCG6G2G3H1H8GCG4G7JFG8GCJ0N0GEG7MFO0G3JFG8L0J0GCG4G6G3GFG3gGFG6G2G3J0K0G4G0G1GFG9gFGCG0G2K0J0H1G0G8GFGDgFG9G0H8J0J0H1G0G8gHFG1G0H8J0M0G1gGFGCN0J0GCG4G6G3gGFGCG4G6G2G3J0N0GFG0HFG1UFGEO0I0G3H1H8GFG0G3GCG0UFGAG3G1G0G8GCG4I0N0GFGEG3G8G7TFGEP0J0GCG4G6G2YFGCG8GCG4G6G2G3J0K0G4H2G7XFG0G8G0G4G0G2K0J0H1G0G8YFH2H1G0H8J0J0H1H8YFG6G2H1G0H8J0N0G1XFQ0J0GCG4G6G2G1G7WFH8GCG4G6G2G3J0N0G3XFG8P0J0H1H8KFGBSFGEG2G3G1G0G8GCJ0N0G7JFG9SFG8P0J0GCG4H2G3JFGDSFH8GCG4G6G2G3J0J0H4H2G1JFGCSFGCH8G4G0G2G1J0J0G1H0G8G0G7IFG9SFGCG2H1G0H8J0J0H1H8GCG7IFG1SFGEG2H1G0H8J0P0IFG0SFGCP0K0G4G6G2G3G1IFGCSFGEG8GCG4G6G2K0P0IFG0JFG8J0G3IFGEP0J0H1H8GCG4IFG1JFG6G2G3H1G9IFGEG2G3G1G0H8J0P0HFGEG1IFGEL0IFGEP0K0G4H2G1G3HFGCG5IFGDG1H8H4G2JFG8GCG4G6G2K0K0G4H2G1G7HFG8G5IFG9G0H8H4G2G7IFH8H4G2K0M0G8G1IFG0G3IFGCG0G2G0G1H0GBIFG2G0G1G0G8K0K0G1H8GDHFGEH3IFH4G2G3H1G8G9IFG2H1G0G8K0N0G1HFG8G0G3HFGEN0IFG8O0L0G6G2G3GFGDG8GCG7IFH1H8GCG4G6G3G7HFG8GCG4G6L0S0G7HFG8N0G7HFG8O0M0G8GCG4G6G2G3G7HFG8G4G6G2G3H1H8IFGEG3G1M0S0G7HFO0G1HFGCO0M0G2H1G0H8G7GFGEG3G1G0H8H4H2G1HFGCG8G4M0M0G2H1G0H8HFGEG3G1G0H8H4H2G1G7GFGCG8G4M0S0HFG8P0G7GFGEO0N0GCG4G6G2G3G1G9H8G4G6G2G3H1H8GCH6G2G3N0,N0H1H8GCG4G6G2G3H1H8GCG4G6G3H1I8N0,P0G6G2G3G1G0H8G4G6G2G3H1H8GCG4G6P0Q0G2G0G1I0G4G0G2G0G1H0G8G0G4Q0Q0H8H4G2G3G1G0H8H4H2H1Q0R0G8G4G6G2G3H1H8H4H2G1R0,S0H1H8G4G6G2G3H1H8S0,V0G3H1H8GCV0,:::::^FS

Below is the rendered image
![demo](https://github.com/ReplyTechnologies/zpl-image-convert/assets/15209819/8b0af07b-b6ee-4ab2-aa09-cb0ec11de33f)

**Comment by DanieLeeuwner** [comment]
@yangjunjie003 can you share the original image?

**Comment by DanieLeeuwner** [comment]
Image compression implementation has issues for both encoding and decoding of ASCII ZPL images.

**Comment by DanieLeeuwner** [comment]
@yangjunjie003 a new version ([0.0.3](https://www.npmjs.com/package/@replytechnologies/zpl-image-convert/v/0.0.3)) of the package has been published to NPM which fixes the issues with ASCII image compression. 

The output of your ZPL is shown below:

![label_ascii](https://github.com/ReplyTechnologies/zpl-image-convert/assets/16599761/72d9169f-09e5-44f3-9cd3-33d24460dc71)

**Comment by yangjunjie003** [comment]
> @yangjunjie003 a new version ([0.0.3](https://www.npmjs.com/package/@replytechnologies/zpl-image-convert/v/0.0.3)) of the package has been published to NPM which fixes the issues with ASCII image compression.
> 
> The output of your ZPL is shown below:
> 
> ![label_ascii](https://private-user-images.githubusercontent.com/16599761/329006461-72d9169f-09e5-44f3-9cd3-33d24460dc71.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyMTcxNDgsIm5iZiI6MTcxNTIxNjg0OCwicGF0aCI6Ii8xNjU5OTc2MS8zMjkwMDY0NjEtNzJkOTE2OWYtMDllNS00NGYzLTljZDMtMzNkMjQ0NjBkYzcxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA5VDAxMDcyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE0NzE3NDZmNWZjYzYwYzMxMDY5YjM5YTFmYmUwMmE4Mjg0OTQ5Y2RlMGYxZTg0ZjZmNmFhNzBjMzRlODQ3Y2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cHYBeSNsu9PCHgpvEAM86I0GegJYuX3biut9GSHadQc)

Yes, this 0.03 is perfect, it successfully parses ZPL into the correct picture, thank you
